strategy:
  matrix:
    node-version: [18.x,20.x]

steps:
  - uses: actions/checkout@v4
  - name: Setup Node
    uses: action/setup-node@v3
    with:
      node-version: ${{ matrix.node-version }}
  - run: npm ci
  - run: npm run build
  - run: npm linkt
